name: Windows Build Environment Setup

on:
  workflow_dispatch:
  push:
    branches: [main]

jobs:
  setup-build-env:
    runs-on: windows-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set PowerShell Execution Policy
        shell: pwsh
        run: |
          Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope CurrentUser

      - name: Run setup_build_env.ps1 as Administrator
        shell: pwsh
        run: |
          pwsh -File ./setup_build_env.ps1
